services:
  caddy:
    ports: !reset []

  backend:
    build:
      target: dev
    command: air
    environment:
      GIN_MODE: "debug"
    ports:
      - "${SERVER_PORT:-8000}:8000"
      - "5864:5864"